#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSDAfBp8t6CDYQuexyhRWNRrQAxYLd6wDrah"
APP_SECRET: "aIfKk/lg6q85dGqlLN4gYGsQgn4Uzz8QDFX2iunywPX2gofJkIa1aI0+aamaKPJvtfgf9+inhRDvdzIi2yYqMwJdd0/PgHQp9Y4jM6GSz3EsswbzRdX8guapJMvY/t9P/2kKkidUnnO6XMX9Te8kpMc7Y5kxjZ7kzKKQImzultTlDm2Nf1s="

#계좌번호 앞 8자리
CANO: "68556858"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1042702603546542143/fFQW1LMH5IzfGMmbnKTCmFFslDE1BZCmPcHKed1a1fiI3Su3VUXC7MbizUsAtnI84p8l"